### ISSUE TITLE
How to get/calculate the groundtruthDist.txt and groundtruthIndices.txt?

### ISSUE THREAD

**Issue by zkchen95** [RUSH-LAB/Flash#7]

**Comment by LeeDark** [comment]
Hi @ZzzackChen! Your question is about SIFT datasets? If yes, then I join the question!

**Comment by wangyiqiu** [comment]
Hi, the groundtruth file for the webspam dataset is here: https://github.com/wangyiqiu/webspam
You may calculate the groundtruth for any dataset using MATLAB or Python
