### ISSUE TITLE
Fast run question

### ISSUE THREAD

**Issue by jinz2014** [RUSH-LAB/Flash#8]
Hi Developers,

I tried to run your tutorial. The time to read the webspam dataset take ~10 min. I would like to run an example using a small dataset. Could you please let me know a small dataset and its settings ? Then I can quickly run an OpenCL application in less than one minute for debugging before using a large dataset.

Thank you for your attention.

**Comment by iitkgpanshu** [comment]
You can use url dataset or RCV1 or virtually any other dataset reported.

(or have an SSD hardrive for webspam ... it will be lot faster)

Anshu
-----------------------------------------------------------------------------
Anshumali Shrivastava
Assistant Professor
Department of Computer Science
Rice University
DH-3118
anshumali@rice.edu
713-348-3049
